FROM python:3.13.5-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /bot_app

COPY prod-requirements.txt .
COPY dev-requirements.txt .
RUN python -m pip install --upgrade pip && \
    python -m pip install -r dev-requirements.txt && \
    apt-get update &&\
    apt-get install --no-install-recommends sqlite3 -y


COPY . .

CMD [ "python", "src/app/main.py" ]