services:
    redis:
        image: redis:7-alpine
        container_name: redis
        volumes:
            - redis_data:/data
        restart: unless-stopped
        env_file:
            - .env

    aiobot:
        build: .
        container_name: aiobot
        depends_on:
            - redis
        env_file:
            - .env
        restart: unless-stopped
        volumes:
            - ./database:/bot_app/database

volumes:
    redis_data:
