"""phone added to Order

Revision ID: 9784faed47d8
Revises: dd7812cd89fe
Create Date: 2025-10-16 23:49:53.353019+03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9784faed47d8'
down_revision: Union[str, Sequence[str], None] = 'dd7812cd89fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('phone', sa.String(length=9), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'phone')
    # ### end Alembic commands ###
